services:
  - type: web
    name: team-activity-tracker
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && cd backend && npm install && cd ../frontend && npm install && npx vite build && cd .. && node verify-build.js
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
